[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/index.html"
[[redirects]]
  from = "/submit-booking/*"
  to = "/api/:splat"
  status = 200
[build]
  functions = "netlify/functions"
  included_files = ["./availableTimeSlots.json"]